### PR TITLE
[toReview] Update to kernel 4.1.35 and mptcp v0.91.3 with UEFI bios support and overthebox subtarget

### PR DESCRIPTION
**Pull request by sduponch**

### CODE REVIEW

**Comment by sduponch** [comment]
Known issues :
- ~~sysupgrade does not work or flash without restoring conf from bootpartition~~
- There is a perfomance issue (-45%) with the DE3815TYBE Intel Nuc althougth that we have a (+25%) on the OverTheBox V2 hardware.
- ~~intel_sst_acpi: intel/fw_sst_22a8.bin is missing.~~ intel_sst_acpi crashdump while firmware load
-  i2c_designware 808622C1:06: couldn't acquire bus ownership (https://bugzilla.kernel.org/show_bug.cgi?id=155241)
- ~~Missing rtl8723bs wifi module (/sys/bus/sdio/devices/mmc0\:0001\:1/uevent)~~

**Comment by debiansid** [comment]
How can I merge it into my local copy of overthebox?

**Comment by sduponch** [comment]
You need to rebuild the whole thing : 

```
git clone git@github.com:sduponch/overthebox.git
cd overthebox
git pull
git checkout kernel_4.1_mptcp_v0.91_efi
./build-image.sh
```

This will build an image with the latest openwrt toolchain, mptcp kernel and overthebox feeds (0.4.19). then you are free to play with feeds.conf to add your local changes/repo.
There still some work to todo and this is only for testing purpose and at your own risk...

**Comment by debiansid** [comment]
Thanks , is it possible to be installed onto x86-64 machine(not NUC)?

**Comment by sduponch** [comment]
Yes, but this mainly optimized for Intel with AES-NI processor (silvermont arch).
You can add more/specific hardware support in kernel by using : 
- make kernel_menuconfig CONFIG_TARGET=subtarget

**Comment by debiansid** [comment]
I believe your mptcp kernel patch is for 4.1.35, but default kernel version in this otb is 4.1.27, so maybe you should check it again

**Comment by debiansid** [comment]
Sun Nov 20 07:52:28 2016 daemon.err uhttpd[3578]: cat: can't open '/proc/net/mptcp_fullmesh': No such file or directory

got lot of this error message in system log

**Comment by sduponch** [comment]
Everything is ok from my side :
root@OpenWrt:~ uname -a
Linux OpenWrt 4.1.27 #1 SMP Fri Nov 18 18:17:54 UTC 2016 x86_64 GNU/Linux
root@OpenWrt:~ dmesg | grep MPTCP
[    1.458698] MPTCP: Stable release v0.91.2 - 8e6d10d6710f
root@OpenWrt:~# cat  /proc/net/mptcp_fullmesh
Index, Address-ID, Backup, IP-address
IPv4, next v4-index: 7
3, 4, 0, 192.168.0.2
IPv6, next v6-index: 0

**Comment by debiansid** [comment]
I changed kernel to 4.1.35 ,coz I did not find the mptcp patch for 4.1.27 from your git

**Comment by sduponch** [comment]
mptcp patch for 4.1.35 apply on 4.1.27

**Comment by debiansid** [comment]
You know what if I am using 4.1.27, there would be no mptcp patched . I will test it again ,thanks for your help. By the way, my otb does not show bandwidth graph on status page. And I have no idea how to make shadowsocks and glorytun working either.

**Comment by debiansid** [comment]
any detail about OverTheBox V2 hardware? still intel NUC but with i3 CPU?

**Comment by sduponch** [comment]
intel cherry trail x5-z8350, quad core atom

**Comment by debiansid** [comment]
still no luck 
```
uname -a
Linux OpenWrt 4.1.27 #1 SMP Tue Nov 22 00:37:26 UTC 2016 x86_64 GNU/Linux
root@OpenWrt:~# dmesg | grep MPTCP
root@OpenWrt:~# cat /proc/net/mptcp_fullmesh
cat: can't open '/proc/net/mptcp_fullmesh': No such file or directory
```
is that because I changed it into x86_64 not silvermont?

**Comment by debiansid** [comment]
ok I found where is my problem, I did not run make kernel_menuconfig to choose mptcp.
now I got mptcp kernel running.
but still have problems on glorytun and shadowsocks, 
btw, Realtime Traffic still show nothing.

**Comment by debiansid** [comment]
@sduponch 
I just installed your newest branch, but my ADSL fiber modem is in bridge mode. Is there a way to hightlight modem when modem is in bridge mode?

**Comment by debiansid** [comment]
I figured it out how to make glorytun and shadowsocks working.

**Comment by sduponch** [comment]
Outdated

**Pull request closed without merging**
